-- INPUT: 
	-- IMPACT
	-- IMPACT_CODES_RAW
-- OUTPUT:
	-- REF_CODES
	-- IMPACT_CLEAN

----------------------------
-- TRANSFORMACE: 
    -- IMPACT_CODES_RAW => REF_CODES
        -- IMPACT_CODES_RAW = https://docs.google.com/spreadsheets/d/1fZENjFwqfzPBhpYKiWzAiefoafT-cFSX/edit?gid=286206321#gid=286206321 (zdroj EIONET.EUROPA.EU)
    -- REF_CODES + IMPACT => IMPACT_CLEAN
----------------------------

-- PŘIDÁVÁM DO TABULKY IMPACT SLOUPEC S KÓDEM ZEMĚ => VZNIK SLOUPCE COUNTRY_CODE_SC
ALTER TABLE IMPACT
ADD COLUMN COUNTRY_CODE_SC VARCHAR(2) AS (LEFT(SITECODE, 2))
;

-- UPDATE TABULKY IMPACT NA UPPERCASE + TRIM
UPDATE IMPACT
SET
      SITECODE = UPPER(TRIM(SITECODE))
    , IMPACTCODE = UPPER(TRIM(IMPACTCODE))
    , DESCRIPTION = UPPER(TRIM(DESCRIPTION))
    , INTENSITY = UPPER(TRIM(INTENSITY))
    , POLLUTIONCODE = UPPER(TRIM(POLLUTIONCODE))
    , OCCURRENCE = UPPER(TRIM(OCCURRENCE))
    , IMPACT_TYPE = UPPER(TRIM(IMPACT_TYPE))
;

-- UPDATE TABULKY IMPACT_CODES_RAW NA UPPERCASE + TRIM
UPDATE IMPACT_CODES_RAW
SET "code" = UPPER(TRIM("code")),
    "code_EDIT" = UPPER(TRIM("code_EDIT")),
    "description_use_for_reporting" = UPPER(TRIM("description_use_for_reporting")),
    "description_corrected" = UPPER(TRIM("description_corrected")),
    "level1_code" = UPPER(TRIM("level1_code")),
    "level1_description_use_for_reporting" = UPPER(TRIM("level1_description_use_for_reporting")),
    "level1_description_corrected" = UPPER(TRIM("level1_description_corrected"))
;

-- VYTVOŘENÍ TABULKY REF_CODES = REFERENČNÍ TABULKA PRO SELECTY BEZ DLOUHÉHO VÝČTU KÓDŮ
CREATE OR REPLACE TABLE REF_CODES AS
SELECT "code" AS CODE
    , "description_use_for_reporting" AS DESCRIPTION_USE_FOR_REPORTING
    , "description_corrected" AS DESCRIPTION_CORRECTED
    , "level1_code" AS LEVEL1_CODE  
    , "level1_description_use_for_reporting" AS LEVEL1_DESCRIPTION_USE_FOR_REPORTING  
    , "level1_description_corrected" AS LEVEL1_DESCRIPTION_CORRECTED
FROM IMPACT_CODES_RAW
;

-- VYTVOŘENÍ TABULKY IMPACT_CLEAN:

CREATE OR REPLACE TABLE IMPACT_CLEAN AS
    SELECT I.IMPACTCODE
          , R.DESCRIPTION_USE_FOR_REPORTING AS DESCRIPTION
          , R.LEVEL1_CODE AS L1_CODE
          , CASE
                WHEN R.LEVEL1_CODE = 'A' THEN 'AGRICULTURE'
                WHEN R.LEVEL1_CODE = 'B' THEN 'FORESTRY'
                WHEN R.LEVEL1_CODE = 'C' THEN 'MINING, QUARRYING & ENERGY PRODUCTION'
                WHEN R.LEVEL1_CODE = 'D' THEN 'TRANSPORTATION & SERVICE INFRASTRUCTURE'
                WHEN R.LEVEL1_CODE = 'E' THEN 'URBANISATION, RESIDENTIAL & COMMERCIAL DEVELOPMENT'
                WHEN R.LEVEL1_CODE = 'F' THEN 'USE OF LIVING RESOURCES (OTHER THAN AGRICULTURE & FORESTRY)'
                WHEN R.LEVEL1_CODE = 'G' THEN 'DISTURBANCES DUE TO HUMAN ACTIVITIES'
                WHEN R.LEVEL1_CODE = 'H' THEN 'POLLUTION'
                WHEN R.LEVEL1_CODE = 'I' THEN 'INVASIVE AND INTRODUCED SPECIES'
                WHEN R.LEVEL1_CODE = 'J' THEN 'MODIFICATION OF NATURAL CONDITIONS'
                WHEN R.LEVEL1_CODE = 'K' THEN 'NATURAL PROCESSES (EXCLUDING CATASTROPHES)'
                WHEN R.LEVEL1_CODE = 'L' THEN 'GEOLOGICAL EVENTS, NATURAL CATASTROPHES'
                WHEN R.LEVEL1_CODE = 'M' THEN 'CLIMATE CHANGE'
                WHEN R.LEVEL1_CODE = 'U' THEN 'UNKNOWN THREAT OR PRESSURE'
                WHEN R.LEVEL1_CODE = 'X' THEN 'NO PRESSURES OR THREATS'
                WHEN R.LEVEL1_CODE = 'XE' THEN 'THREATS AND PRESSURES FROM OUTSIDE THE EU TERRITORY'
                WHEN R.LEVEL1_CODE = 'XO' THEN 'THREATS AND PRESSURES FROM OUTSIDE THE MEMBER STATE'
            END AS L1_MEANING
          , CASE
                WHEN I.IMPACTCODE LIKE '%.%.%' THEN 'L4'
                WHEN I.IMPACTCODE LIKE '%.%' THEN 'L3'
                WHEN TRY_TO_NUMBER(RIGHT(I.IMPACTCODE, LENGTH(I.IMPACTCODE) - 1)) IS NOT NULL THEN 'L2'
                ELSE 'L1'
            END AS IMPACT_CODE_HIERARCHY
          , CASE
                WHEN I.OCCURRENCE IS NULL OR I.OCCURRENCE IN('', 'A', '-') THEN 'UNKNOWN'
                ELSE I.OCCURRENCE
            END AS OCCURRENCE
          , CASE
                WHEN I.IMPACT_TYPE IS NULL OR I.IMPACT_TYPE = '' THEN 'UNKNOWN'
                ELSE I.IMPACT_TYPE
            END AS IMPACT_TYPE
          , CASE
                WHEN I.INTENSITY IS NULL OR I.INTENSITY IN('A', '', 'O', 'X', 'C', 'E', 'I') THEN 'UNKNOWN'
                ELSE I.INTENSITY
            END AS INTENSITY
          , I.COUNTRY_CODE_SC AS COUNTRY_CODE
          , I.SITECODE
          , N.SITETYPE
          , TRY_CAST(N.AREAHA AS NUMBER(18,4)) AS AREA_HA
          , TRY_CAST(N.AREAHA AS NUMBER(18,4)) / 100 AS AREA_KM2
          , TRY_CAST(N.AREAHA AS NUMBER(18,4)) * 10000 AS AREA_M2
          , TRY_CAST(N.LATITUDE AS NUMBER(10,6)) AS LATITUDE
          , TRY_CAST(N.LONGITUDE AS NUMBER(10,6)) AS LONGITUDE
    FROM IMPACT AS I
    INNER JOIN REF_CODES AS R 
        ON I.IMPACTCODE = R.CODE
    LEFT JOIN NATURA2000SITES AS N 
        ON I.SITECODE = N.SITECODE
;