-- INPUT: 
	-- IMPACT
	-- IMPACT_CODES_RAW
-- OUTPUT:
	-- REF_CODES
	-- IMPACT_CLEAN

----------------------------
-- TRANSFORMACE: 
    -- IMPACT_CODES_RAW => REF_CODES
        -- IMPACT_CODES_RAW = https://docs.google.com/spreadsheets/d/1fZENjFwqfzPBhpYKiWzAiefoafT-cFSX/edit?gid=286206321#gid=286206321 (zdroj EIONET.EUROPA.EU)
    -- REF_CODES + IMPACT => IMPACT_CLEAN
----------------------------

-- PŘIDÁVÁM DO TABULKY IMPACT SLOUPEC S KÓDEM ZEMĚ => VZNIK SLOUPCE COUNTRY_CODE_SC
ALTER TABLE IMPACT
ADD COLUMN COUNTRY_CODE_SC VARCHAR(2) AS (LEFT(SITECODE, 2))
;

-- UPDATE TABULKY IMPACT NA UPPERCASE + TRIM
UPDATE IMPACT
SET
      SITECODE = UPPER(TRIM(SITECODE))
    , IMPACTCODE = UPPER(TRIM(IMPACTCODE))
    , DESCRIPTION = UPPER(TRIM(DESCRIPTION))
    , INTENSITY = UPPER(TRIM(INTENSITY))
    , POLLUTIONCODE = UPPER(TRIM(POLLUTIONCODE))
    , OCCURRENCE = UPPER(TRIM(OCCURRENCE))
    , IMPACT_TYPE = UPPER(TRIM(IMPACT_TYPE))
;

-- UPDATE TABULKY IMPACT_CODES_RAW NA UPPERCASE + TRIM
UPDATE IMPACT_CODES_RAW
SET "code" = UPPER(TRIM("code")),
    "code_EDIT" = UPPER(TRIM("code_EDIT")),
    "description_use_for_reporting" = UPPER(TRIM("description_use_for_reporting")),
    "description_corrected" = UPPER(TRIM("description_corrected")),
    "level1_code" = UPPER(TRIM("level1_code")),
    "level1_description_use_for_reporting" = UPPER(TRIM("level1_description_use_for_reporting")),
    "level1_description_corrected" = UPPER(TRIM("level1_description_corrected"))
;

-- VYTVOŘENÍ TABULKY REF_CODES = REFERENČNÍ TABULKA PRO SELECTY BEZ DLOUHÉHO VÝČTU KÓDŮ
CREATE OR REPLACE TABLE REF_CODES AS
SELECT "code" AS CODE
    , "description_use_for_reporting" AS DESCRIPTION_USE_FOR_REPORTING
    , "description_corrected" AS DESCRIPTION_CORRECTED
    , "level1_code" AS LEVEL1_CODE  
    , "level1_description_use_for_reporting" AS LEVEL1_DESCRIPTION_USE_FOR_REPORTING  
    , "level1_description_corrected" AS LEVEL1_DESCRIPTION_CORRECTED
FROM IMPACT_CODES_RAW
;

-- VYTVOŘENÍ TABULKY IMPACT_CLEAN:

CREATE OR REPLACE TABLE IMPACT_CLEAN AS
    SELECT I.IMPACTCODE
          , R.DESCRIPTION_USE_FOR_REPORTING AS DESCRIPTION
          , R.LEVEL1_CODE AS L1_CODE
          , CASE
                WHEN R.LEVEL1_CODE = 'A' THEN 'AGRICULTURE'
                WHEN R.LEVEL1_CODE = 'B' THEN 'FORESTRY'
                WHEN R.LEVEL1_CODE = 'C' THEN 'MINING, QUARRYING & ENERGY PRODUCTION'
                WHEN R.LEVEL1_CODE = 'D' THEN 'TRANSPORTATION & SERVICE INFRASTRUCTURE'
                WHEN R.LEVEL1_CODE = 'E' THEN 'URBANISATION, RESIDENTIAL & COMMERCIAL DEVELOPMENT'
                WHEN R.LEVEL1_CODE = 'F' THEN 'USE OF LIVING RESOURCES (OTHER THAN AGRICULTURE & FORESTRY)'
                WHEN R.LEVEL1_CODE = 'G' THEN 'DISTURBANCES DUE TO HUMAN ACTIVITIES'
                WHEN R.LEVEL1_CODE = 'H' THEN 'POLLUTION'
                WHEN R.LEVEL1_CODE = 'I' THEN 'INVASIVE AND INTRODUCED SPECIES'
                WHEN R.LEVEL1_CODE = 'J' THEN 'MODIFICATION OF NATURAL CONDITIONS'
                WHEN R.LEVEL1_CODE = 'K' THEN 'NATURAL PROCESSES (EXCLUDING CATASTROPHES)'
                WHEN R.LEVEL1_CODE = 'L' THEN 'GEOLOGICAL EVENTS, NATURAL CATASTROPHES'
                WHEN R.LEVEL1_CODE = 'M' THEN 'CLIMATE CHANGE'
                WHEN R.LEVEL1_CODE = 'U' THEN 'UNKNOWN THREAT OR PRESSURE'
                WHEN R.LEVEL1_CODE = 'X' THEN 'NO PRESSURES OR THREATS'
                WHEN R.LEVEL1_CODE = 'XE' THEN 'THREATS AND PRESSURES FROM OUTSIDE THE EU TERRITORY'
                WHEN R.LEVEL1_CODE = 'XO' THEN 'THREATS AND PRESSURES FROM OUTSIDE THE MEMBER STATE'
            END AS L1_MEANING
          , CASE
                WHEN I.IMPACTCODE LIKE '%.%.%' THEN 'L4'
                WHEN I.IMPACTCODE LIKE '%.%' THEN 'L3'
                WHEN TRY_TO_NUMBER(RIGHT(I.IMPACTCODE, LENGTH(I.IMPACTCODE) - 1)) IS NOT NULL THEN 'L2'
                ELSE 'L1'
            END AS IMPACT_CODE_HIERARCHY
          , CASE
                WHEN I.OCCURRENCE IS NULL OR I.OCCURRENCE IN('', 'A', '-') THEN 'UNKNOWN'
                ELSE I.OCCURRENCE
            END AS OCCURRENCE
          , CASE
                WHEN I.IMPACT_TYPE IS NULL OR I.IMPACT_TYPE = '' THEN 'UNKNOWN'
                ELSE I.IMPACT_TYPE
            END AS IMPACT_TYPE
          , CASE
                WHEN I.INTENSITY IS NULL OR I.INTENSITY IN('A', '', 'O', 'X', 'C', 'E', 'I') THEN 'UNKNOWN'
                ELSE I.INTENSITY
            END AS INTENSITY
          , I.COUNTRY_CODE_SC AS COUNTRY_CODE
          , I.SITECODE
          , N.SITETYPE
          , TRY_CAST(N.AREAHA AS NUMBER(18,4)) AS AREA_HA
          , TRY_CAST(N.AREAHA AS NUMBER(18,4)) / 100 AS AREA_KM2
          , TRY_CAST(N.AREAHA AS NUMBER(18,4)) * 10000 AS AREA_M2
          , TRY_CAST(N.LATITUDE AS NUMBER(10,6)) AS LATITUDE
          , TRY_CAST(N.LONGITUDE AS NUMBER(10,6)) AS LONGITUDE
    FROM IMPACT AS I
    INNER JOIN REF_CODES AS R 
        ON I.IMPACTCODE = R.CODE
    LEFT JOIN NATURA2000SITES AS N 
        ON I.SITECODE = N.SITECODE
;

----------------------------
-- EXPLORACE & ČIŠTĚNÍ
----------------------------

-- ENTITA IMPACT
----------------------------------------------------------------------------------------------------------------

-- 200 695 = VYBERE VŠE Z TABULKY IMPACT
SELECT *
FROM IMPACT
;

-- 0 = V TABULCE NEJSOU ŽÁDNÉ ZÁZNAMY S NEVYPLNĚNÝM SITECODE = KÓD PLOCHY, UNIKÁTNÍ IDENTIFIKÁTOR
SELECT *
FROM IMPACT
WHERE SITECODE IS NULL OR TRIM(SITECODE) = ''
;

-- NEPOUŽITELNÉ HODNOTY
----------------------------------------------------------------------------------------------------------------

-- 6345 = POČET PRÁZDNÝCH ZÁZNAMŮ VE SLOUPCI IMPACTCODE
SELECT COUNT(*) AS POCET_PRAZDNYCH
FROM IMPACT
WHERE IMPACTCODE IS NULL OR TRIM(IMPACTCODE) = ''
;

-- 0 = VYPÍŠE ZÁZNAMY, KDE JE IMPACTCODE NULL
SELECT *
FROM IMPACT
WHERE IMPACTCODE IS NULL
;

-- 6345 = VYPÍŠE ZÁZNAMY, KDE JE IMPACTCODE ''
SELECT *
FROM IMPACT
WHERE TRIM(IMPACTCODE) = ''
;

-- => VŠECHNY NEVYPLNĚNÉ IMPACTCODY JSOU ''

-- 6345 = POČET PRÁZDNÝCH ZÁZNAMŮ VE SLOUPCI IMPACTCODE A ZÁROVEŇ DESCRIPTION
-- = TYTO ZÁZNAMY NEMŮŽU KATEGORIZOVAT PODLE NÁZVU
SELECT *
FROM IMPACT
WHERE (IMPACTCODE IS NULL OR TRIM(IMPACTCODE) = '') AND (DESCRIPTION IS NULL OR TRIM(DESCRIPTION) = '')
;

-- 0 - OVĚŘENÍ SELECTU VÝŠE: HLEDÁM ZÁZNAMY, KDE JE DESCRIPTION, ALE NENÍ TAM IMPACTCODE:
SELECT *
FROM IMPACT
WHERE (IMPACTCODE IS NULL OR TRIM(IMPACTCODE) = '') AND (DESCRIPTION IS NOT NULL AND TRIM(DESCRIPTION) != '')
;

-- => ZÁVĚR: U VŠECH ZÁZNAMŮ, KDE NENÍ VYPLNĚNÝ IMPACTCODE, NENÍ VYPLNĚNÉ ANI DESCRIPTION = NEPOUŽITELNÉ ZÁZNAMY
        -- 6345 záznamů bude UNKNOWN nebo N/A? 
        -- Znamená nevyplněný IMPACTCODE/DESCRIPTION, že u dané plošky neexistuje impact, nebo že pouze není uveden?


-- 6 317 = MALTA A FINSKO NEMAJÍ ŽÁDNÉ VALIDNÍ ZÁZNAMY V TABULCE IMPACT = U VŠECH SITES VE FINSKU A NA MALTĚ NENÍ IMPACTCODE A DESCRIPTION
SELECT * 
FROM IMPACT
WHERE COUNTRY_CODE_SC IN('FI', 'MT') AND IMPACTCODE = '' AND DESCRIPTION = ''
;

SELECT *
FROM IMPACT
WHERE COUNTRY_CODE_SC IN('FI', 'MT') AND IMPACTCODE <> ''
;

-- ALE: EXISTUJE 410 ZÁZNAMŮ, KDE ZNÁM IMPACTCODE, ALE NEZNÁM DESCRIPTION:
SELECT *
FROM IMPACT
WHERE (DESCRIPTION IS NULL OR TRIM(DESCRIPTION) = '') AND (IMPACTCODE IS NOT NULL AND TRIM(IMPACTCODE) != '')
;

-- => U TĚCHTO 410 ZÁZNAMŮ SI MŮŽU DOPLNIT HODNOTU DESCRIPTION PODLE OSTATNÍCH ZÁZNAMŮ?
-- CHCI SI PROHLÉDNOUT, O KTERÉ KÓDY JDE -> 410 ZÁZNAMŮ OBSAHUJE 92 UNIKÁTNÍCH KÓDŮ:

-- 92 = POČET UNIKÁTNÍCH IMPACTCODŮ, U KTERÝCH NEMÁM DESCRIPTION
SELECT DISTINCT IMPACTCODE, COUNT(*) AS POCET_ZAZNAMU
FROM IMPACT
WHERE (DESCRIPTION IS NULL OR TRIM(DESCRIPTION) = '') AND (IMPACTCODE IS NOT NULL AND TRIM(IMPACTCODE) != '')
GROUP BY IMPACTCODE
-- ORDER BY POCET_ZAZNAMU DESC
ORDER BY IMPACTCODE
;

-- ZJIŠTĚNÍ => JDE O 410 ZÁZNAMŮ, KDE JE ŠPATNĚ UVEDEN IMPACTCODE


-- IMPACTCODE / DESCRIPTION
----------------------------------------------------------------------------------------------------------------

-- 194 350 = VŠECHNY NENULOVÉ ZÁZNAMY VE SLOUPCI IMPACTCODE
SELECT COUNT(IMPACTCODE)
FROM IMPACT
WHERE IMPACTCODE IS NOT NULL AND TRIM(IMPACTCODE) != ''
;

-- 500 = POČET UNIKÁTNÍCH HODNOT VE SLOUPCI IMPACTCODE (bez null a prázdného stringu - s prázdným stringem 501)
SELECT COUNT(DISTINCT IMPACTCODE)
FROM IMPACT
WHERE TRIM(IMPACTCODE) != '' 
;

-- 500 = SEZNAM UNIKÁTNÍCH HODNOT VE SLOUPCI IMPACTCODE (bez null a prázdného stringu)
SELECT DISTINCT IMPACTCODE
FROM IMPACT
WHERE TRIM(IMPACTCODE) != ''
ORDER BY IMPACTCODE
;

-- !!! duplicity !!!
-- např. I 01 / I01 - J02,06,02 / J02.06.02 - J02.09 / J02.09.


-- ČIŠTĚNÍ IMPACTCODE
----------------------------------------------------------------------------------------------------------------

-- 410 = SEZNAM ZÁZNAMŮ S CHYBNĚ UVEDENÝM IMPACTCODE:
SELECT I.*
FROM IMPACT AS I
LEFT JOIN REF_CODES AS R
    ON I.IMPACTCODE = R.CODE
WHERE R.CODE IS NULL
    AND I.IMPACTCODE IS NOT NULL
    AND I.IMPACTCODE != ''
;

-- ALTERNATIVNĚ PŘES NOT IN()
            SELECT *
            FROM IMPACT
            WHERE TRIM(IMPACTCODE) NOT IN( -- SPRÁVNĚ ZADANÉ HODNOTY:
            'A', 'A01', 'A02', 'A02.01', 'A02.02', 'A02.03', 'A03', 'A03.01', 'A03.02', 'A03.03', 'A04', 'A04.01', 'A04.01.01', 'A04.01.02', 'A04.01.03', 'A04.01.04', 'A04.01.05', 'A04.02', 'A04.02.01', 'A04.02.02', 'A04.02.03', 'A04.02.04', 'A04.02.05', 'A04.03', 'A05', 'A05.01',  'A05.02', 'A05.03', 'A06', 'A06.01', 'A06.01.01', 'A06.01.02', 'A06.02', 'A06.02.01', 'A06.02.02', 'A06.03', 'A06.04', 'A07', 'A08', 'A09', 'A10', 'A10.01', 'A10.02', 'A11', 'B', 'B01', 'B01.01', 'B01.02', 'B02', 'B02.01', 'B02.01.01', 'B02.01.02', 'B02.02', 'B02.03', 'B02.04', 'B02.05', 'B02.06', 'B03', 'B04', 'B05', 'B06', 'B07', 'C', 'C01', 'C01.01', 'C01.01.01', 'C01.01.02', 'C01.02', 'C01.03', 'C01.03.01', 'C01.03.02', 'C01.04', 'C01.04.01', 'C01.04.02', 'C01.05', 'C01.05.01', 'C01.05.02', 'C01.06', 'C01.07', 'C02', 'C02.01', 'C02.02', 'C02.03', 'C02.04', 'C02.05', 'C03', 'C03.01', 'C03.02', 'C03.03', 'C03.04', 'D', 'D01', 'D01.01', 'D01.02', 'D01.03', 'D01.04', 'D01.05', 'D01.06', 'D02', 'D02.01', 'D02.01.01', 'D02.01.02', 'D02.02', 'D02.03', 'D02.09', 'D03', 'D03.01', 'D03.01.01', 'D03.01.02', 'D03.01.03', 'D03.01.04', 'D03.02', 'D03.02.01', 'D03.02.02', 'D03.03', 'D04', 'D04.01', 'D04.02', 'D04.03', 'D05', 'D06', 'E', 'E01', 'E01.01', 'E01.02', 'E01.03', 'E01.04', 'E02', 'E02.01', 'E02.02', 'E02.03', 'E03', 'E03.01', 'E03.02', 'E03.03', 'E03.04', 'E03.04.01', 'E04', 'E04.01', 'E04.02', 'E05', 'E06', 'E06.01', 'E06.02', 'F', 'F01', 'F01.01', 'F01.02', 'F01.03', 'F02', 'F02.01', 'F02.01.01', 'F02.01.02', 'F02.01.03', 'F02.01.04', 'F02.02', 'F02.02.01', 'F02.02.02', 'F02.02.03', 'F02.02.04', 'F02.02.05', 'F02.03', 'F02.03.01', 'F02.03.02', 'F02.03.03', 'F03', 'F03.01', 'F03.01.01', 'F03.02', 'F03.02.01', 'F03.02.02', 'F03.02.03', 'F03.02.04', 'F03.02.05', 'F03.02.09', 'F04', 'F04.01', 'F04.02', 'F04.02.01', 'F04.02.02', 'F05', 'F05.01', 'F05.02', 'F05.03', 'F05.04', 'F05.05', 'F05.06', 'F05.07', 'F06', 'F06.01', 'G', 'G01', 'G01.01', 'G01.01.01', 'G01.01.02', 'G01.02', 'G01.03', 'G01.03.01', 'G01.03.02', 'G01.04', 'G01.04.01', 'G01.04.02', 'G01.04.03', 'G01.05', 'G01.06', 'G01.07', 'G01.08', 'G02', 'G02.01', 'G02.02', 'G02.03', 'G02.04', 'G02.05', 'G02.06', 'G02.07', 'G02.08', 'G02.09', 'G02.10', 'G03', 'G04', 'G04.01', 'G04.02', 'G05', 'G05.01', 'G05.02', 'G05.03', 'G05.04', 'G05.05', 'G05.06', 'G05.07', 'G05.08', 'G05.09', 'G05.10', 'G05.11', 'H', 'H01', 'H01.01', 'H01.02', 'H01.03', 'H01.04', 'H01.05', 'H01.06', 'H01.07', 'H01.08', 'H01.09', 'H02', 'H02.01', 'H02.02', 'H02.03', 'H02.04', 'H02.05', 'H02.06', 'H02.07', 'H02.08', 'H03', 'H03.01', 'H03.02', 'H03.02.01', 'H03.02.02', 'H03.02.03', 'H03.02.04', 'H03.03', 'H04', 'H04.01', 'H04.02', 'H04.03', 'H05', 'H05.01', 'H06', 'H06.01', 'H06.01.01', 'H06.01.02', 'H06.02', 'H06.03', 'H06.04', 'H06.05', 'H07', 'I', 'I01', 'I02', 'I03', 'I03.01', 'I03.02', 'J', 'J01', 'J01.01', 'J01.02', 'J01.03', 'J02', 'J02.01', 'J02.01.01', 'J02.01.02', 'J02.01.03', 'J02.01.04', 'J02.02', 'J02.02.01', 'J02.02.02', 'J02.03', 'J02.03.01', 'J02.03.02', 'J02.04', 'J02.04.01', 'J02.04.02', 'J02.05', 'J02.05.01', 'J02.05.02', 'J02.05.03', 'J02.05.04', 'J02.05.05', 'J02.05.06', 'J02.06', 'J02.06.01', 'J02.06.02', 'J02.06.03', 'J02.06.04', 'J02.06.05', 'J02.06.06', 'J02.06.07', 'J02.06.08', 'J02.06.09', 'J02.06.10', 'J02.07', 'J02.07.01', 'J02.07.02', 'J02.07.03', 'J02.07.04', 'J02.07.05', 'J02.08', 'J02.08.01', 'J02.08.02', 'J02.08.03', 'J02.08.04', 'J02.09.', 'J02.09.01', 'J02.09.02', 'J02.10', 'J02.11', 'J02.11.01', 'J02.11.02', 'J02.12', 'J02.12.01', 'J02.12.02', 'J02.13', 'J02.14', 'J02.15', 'J03', 'J03.01', 'J03.01.01', 'J03.02', 'J03.02.01', 'J03.02.02', 'J03.02.03', 'J03.03', 'J03.04', 'K', 'K01', 'K01.01', 'K01.02', 'K01.03', 'K01.04', 'K01.05', 'K02', 'K02.01', 'K02.02', 'K02.03', 'K02.04', 'K03', 'K03.01', 'K03.02', 'K03.03', 'K03.04', 'K03.05', 'K03.06', 'K03.07', 'K04', 'K04.01', 'K04.02', 'K04.03', 'K04.04', 'K04.05', 'K05', 'K05.01', 'K05.02', 'K06', 'L', 'L01', 'L02', 'L03', 'L04', 'L05', 'L06', 'L07', 'L08', 'L09', 'L10', 'M', 'M01', 'M01.01', 'M01.02', 'M01.03', 'M01.04', 'M01.05', 'M01.06', 'M01.07', 'M02', 'M02.01', 'M02.02', 'M02.03', 'M02.04', 'U', 'X', 'XE', 'XO')
        AND TRIM(IMPACTCODE) <> ''
        AND IMPACTCODE IS NOT NULL
        ;

-- 92 = SEZNAM UNIKÁTNÍCH IMPACTCODŮ, KTERÉ JSOU CHYBNĚ ZADANÉ (CHYBNĚ ZADANÝ = NEKORESPONDUJE S TABULKOU LIST_THREADS_PRESSURES)
SELECT DISTINCT I.IMPACTCODE
FROM IMPACT AS I
LEFT JOIN REF_CODES AS R ON
    I.IMPACTCODE = R.CODE
WHERE R.CODE IS NULL
    AND I.IMPACTCODE IS NOT NULL
    AND I.IMPACTCODE <> ''
;

-- VÝSLEDKY 410 / 92 VYCHÁZÍ I U ZÁZNAMŮ, KDE JE ZADANÝ IMPACTCODE, ALE NENÍ UVEDENÁ DESCRIPTION
    -- => ZAHRNUJÍ TYTO DVA SELEKTY STEJNÉ ZÁZNAMY?

-- 1. SELECT (-- 410 = SEZNAM ZÁZNAMŮ S CHYBNĚ UVEDENÝM IMPACTCODE:)
SELECT I.*
FROM IMPACT AS I
LEFT JOIN REF_CODES AS R
    ON I.IMPACTCODE = R.CODE
WHERE R.CODE IS NULL
    AND I.IMPACTCODE IS NOT NULL
    AND I.IMPACTCODE != ''
;

-- 2. SELECT (-- ALE - 410 = EXISTUJE 410 ZÁZNAMŮ, KDE ZNÁM IMPACTCODE, ALE NEZNÁM DESCRIPTION:)
SELECT *
FROM IMPACT
WHERE (DESCRIPTION IS NULL OR TRIM(DESCRIPTION) = '') AND (IMPACTCODE IS NOT NULL AND TRIM(IMPACTCODE) != '');

-- 3A. OVĚŘOVACÍ QUERY = ZJISTÍ, ZDA JE V DOTAZU 1 NĚCO, CO CHYBÍ V DOTAZU 2 => Query produced no results.
SELECT *
FROM (
    SELECT I.*
    FROM IMPACT AS I
    LEFT JOIN REF_CODES AS R
        ON I.IMPACTCODE = R.CODE
    WHERE R.CODE IS NULL
        AND I.IMPACTCODE IS NOT NULL
        AND I.IMPACTCODE != ''
     )
MINUS
SELECT *
FROM (
    SELECT *
    FROM IMPACT
    WHERE (DESCRIPTION IS NULL OR TRIM(DESCRIPTION) = '') 
        AND (IMPACTCODE IS NOT NULL 
        AND TRIM(IMPACTCODE) != '')
     )
;

-- 3B. OVĚŘOVACÍ QUERY = ZJISTÍ, ZDA JE V DOTAZU 2 NĚCO, CO CHYBÍ V DOTAZU 1 => Query produced no results.
SELECT *
FROM (
    SELECT *
    FROM IMPACT
    WHERE (DESCRIPTION IS NULL OR TRIM(DESCRIPTION) = '') 
    AND (IMPACTCODE IS NOT NULL AND TRIM(IMPACTCODE) != '')
     )
MINUS
SELECT *
FROM (
    SELECT I.*
    FROM IMPACT AS I
    LEFT JOIN REF_CODES AS R
        ON I.IMPACTCODE = R.CODE
    WHERE R.CODE IS NULL
        AND I.IMPACTCODE IS NOT NULL
        AND I.IMPACTCODE != ''
     )
;

-- ===> ZÁVĚR: SELECT 1 A SELECT 2 VRÁTÍ STEJNÝCH 410 ZÁZNAMŮ. JDE O ZÁZNAMY, VE KTERÝCH JE CHYBNĚ UVEDEN IMPACTCODE A ZÁROVEŇ NEMAJÍ DESCRIPTION => JSOU NEPOUŽITELNÉ.


-- 193 940 = VRÁTÍ VŠECHNY ZÁZNAMY, KTERÉ JSOU NOT NULL, NEJSOU '' A MAJÍ SPRÁVNĚ ZADANÝ IMPACTCODE = ČISTÁ DATA VE SLOUPCI IMPACTCODE
SELECT *
FROM IMPACT AS I
INNER JOIN REF_CODES AS R ON
    I.IMPACTCODE = R.CODE
;

-- 408 = VRÁTÍ UNIKÁTNÍ IMPACTCODE PO ČIŠTĚNÍ DAT
SELECT DISTINCT I.IMPACTCODE
FROM IMPACT AS I
INNER JOIN REF_CODES AS R ON I.IMPACTCODE = R.CODE
    AND I.IMPACTCODE IS NOT NULL
    AND TRIM(I.IMPACTCODE) <> ''
;

-- 5 = POČET KÓDŮ Z TABULKY REF_CODES, KTERÉ NENAJDEME V DATECH IMPACT
SELECT R.*
FROM REF_CODES AS R
LEFT JOIN IMPACT AS I
    ON R.CODE = I.IMPACTCODE
WHERE I.IMPACTCODE IS NULL
;

-- VSUVKA: KTERÉ ZEMĚ ŠPATNĚ ZADALY IMPACTCODE?
----------------------------------------------------------------------------------------------------------------

-- SEZNAM ZEMÍ S CHYBNÝMI ZÁZNAMY:
SELECT DISTINCT SUBSTR(SITECODE, 1, 2) AS COUNTRY
FROM IMPACT
WHERE (DESCRIPTION IS NULL OR TRIM(DESCRIPTION) = '')
  AND (IMPACTCODE IS NOT NULL 
  AND TRIM(IMPACTCODE) != '')
;

-- POČET ZÁZNAMŮ PRO KAŽDOU ZEMI S CHYBNÝMI ZÁZNAMY:
SELECT DISTINCT SUBSTR(SITECODE, 1, 2) AS COUNTRY
    , COUNT(*) AS POCET_CHYBNYCH_ZAZNAMU
FROM IMPACT
WHERE (DESCRIPTION IS NULL OR TRIM(DESCRIPTION) = '')
    AND (IMPACTCODE IS NOT NULL 
    AND TRIM(IMPACTCODE) != '')
GROUP BY COUNTRY
ORDER BY POCET_CHYBNYCH_ZAZNAMU DESC
;

-- FUTURE PROJECT: 
    -- KOLIK MAJÍ ALE DANÉ ZEMĚ SPRÁVNĚ UVEDENÝCH ZÁZNAMŮ (POMĚR CELKOVÉ VS. CHYBNÉ VYPLNĚNÍ VS. NULL/'')
    -- MAJÍ KONKRÉTNÍ STÁTY NĚJAKÉ NEŠVARY? NAPŘ. ŘEKOVÉ MAJÍ V CHYBNÉM VÝČTU "Α04.03", COŽ SE TVÁŘÍ JAKO SPRÁVNÝ FORMÁT, ALE TO "A" JE VE SKUTEČNOSTI ALFA. AW.


----------------------------------------------------------------------------------------------------------------
-- REKAPITULACE ČIŠTĚNÍ SLOUPCE IMPACTCODE:
----------------------------------------------------------------------------------------------------------------
-- 200 695 = VŠE Z TABULKY IMPACT
-- 6 345 = POČET PRÁZDNÝCH ZÁZNAMŮ VE SLOUPCI IMPACTCODE A ZÁROVEŇ DESCRIPTION (NULL + '')
-- 194 350 = VŠECHNY NENULOVÉ/NE-'' ZÁZNAMY VE SLOUPCI IMPACTCODE
-- 410 = ZÁZNAMY, VE KTERÝCH JE CHYBNĚ UVEDEN IMPACTCODE A ZÁROVEŇ NEMAJÍ DESCRIPTION => JSOU NEPOUŽITELNÉ
-- 193 940 = VŠECHNY ZÁZNAMY, KTERÉ NEJSOU NULL NEBO '' A MAJÍ SPRÁVNĚ ZADANÝ IMPACTCODE => ČISTÁ DATA VE SLOUPCI IMPACTCODE


-- ROZDĚLENÍ IMPACTCODE = SLOUPEC CODE_HIE
----------------------------------------------------------------------------------------------------------------
SELECT
    IMPACTCODE,
    CASE
        WHEN IMPACTCODE LIKE '%.%.%' THEN 'L4'
        WHEN IMPACTCODE LIKE '%.%' THEN 'L3'
        WHEN TRY_TO_NUMBER(RIGHT(IMPACTCODE, LEN(IMPACTCODE) - 1)) IS NOT NULL THEN 'L2'
        ELSE 'L1'
    END AS CODE_HIE
FROM IMPACT;

-- DESCRIPTION:
----------------------------------------------------------------------------------------------------------------

-- 0 = POČET ZÁZNAMŮ S VYČIŠTĚNÝM SITECODE A BEZ DESCRIPTION
SELECT COUNT(I.*) AS POCET_BEZ_DESCRIPTION
FROM IMPACT AS I
INNER JOIN REF_CODES AS R ON
    I.IMPACTCODE = R.CODE
WHERE (TRIM(DESCRIPTION) = '' OR DESCRIPTION IS NULL)
;

-- VRÁTÍ AGREGAČNÍ PŘEHLED PRO UNIKÁTNÍ ČISTÉ IMPACTCODY:
    --> VÝSLEDEK: KAŽDÝ IMPACTCODE MÁ V TABULCE IMPACT PRÁVĚ JEDNU DESCRIPTION
    -- Z PŘEDCHOZÍ ANALÝZY VÍM, ŽE KAŽDÝ ZÁZNAM, KDE JE SPRÁVNĚ VYPLNĚNÝ SIDECODE, MÁ I VYPLNĚNÉ DESCRIPTION (V DESCRIPTION NENÍ '' ANI NULL)
SELECT 
    I.IMPACTCODE,
    COUNT(DISTINCT I.DESCRIPTION) AS POCET_DESCRIPTION
FROM IMPACT AS I
INNER JOIN REF_CODES AS R
    ON I.IMPACTCODE = R.CODE
GROUP BY I.IMPACTCODE
ORDER BY I.IMPACTCODE DESC
;

-- VRÁTÍ AGREGAČNÍ PŘEHLED PRO UNIKÁTNÍ DESCRIPTION:
    --> VÝSLEDEK: 
        -- DESCRIPTION "WAVE EXPOSURE CHANGES" ODPOVÍDÁ 2 KÓDŮM
        -- DESCRIPTION "INTRODUCTION OF DISEASE (MICROBIAL PATHOGENS)" ODPOVÍDÁ 2 KÓDŮM
SELECT 
    I. DESCRIPTION
    , COUNT(DISTINCT I.IMPACTCODE) AS POCET_IMPACTCODE
FROM IMPACT AS I
INNER JOIN REF_CODES AS R 
    ON I.IMPACTCODE = R.CODE
WHERE I.IMPACTCODE <> ''
    AND I.IMPACTCODE IS NOT NULL
    AND I.DESCRIPTION <> ''
    AND I.DESCRIPTION IS NOT NULL
GROUP BY I.DESCRIPTION
ORDER BY POCET_IMPACTCODE DESC
;

-- VRÁTÍ DVA KÓDY PRO DESCRIPTION "WAVE EXPOSURE CHANGES": M01.06, J02.05.06 => SEDÍ S TABULKOU LISTS_THREATS_PRESSURES
SELECT DISTINCT IMPACTCODE
FROM IMPACT
WHERE TRIM(DESCRIPTION) = 'WAVE EXPOSURE CHANGES'
;

-- VRÁTÍ DVA KÓDY PRO DESCRIPTION "INTRODUCTION OF DISEASE (MICROBIAL PATHOGENS)": K03.03, K04.03 => SEDÍ S TABULKOU LISTS_THREATS_PRESSURES
SELECT DISTINCT IMPACTCODE
FROM IMPACT
WHERE TRIM(DESCRIPTION) = 'INTRODUCTION OF DISEASE (MICROBIAL PATHOGENS)'
;

-- INTRODUCTION OF DISEASE (MICROBIAL PATHOGENS) a WAVE EXPOSURE CHANGES vyjdou jako 2
SELECT DESCRIPTION_USE_FOR_REPORTING, COUNT(*)
FROM REF_CODES
GROUP BY DESCRIPTION_USE_FOR_REPORTING
HAVING COUNT(*) > 1
;

-- 189 210 = ZÁZNAMY, KTERÉ MAJÍ V POŘÁDKU IMPACTCODE A JEJICH DESCRIPTION ODPOVÍDÁ DESCRIPTION_USE_FOR_REPORTING V REFERENČNÍ TABULCE.
WITH REF_DESC AS (
    SELECT DISTINCT DESCRIPTION_USE_FOR_REPORTING
    FROM REF_CODES
                 )
SELECT I.*
FROM IMPACT AS I
INNER JOIN REF_CODES AS R_CODE 
    ON I.IMPACTCODE = R_CODE.CODE
INNER JOIN REF_DESC AS R_DESC 
    ON I.DESCRIPTION = R_DESC.DESCRIPTION_USE_FOR_REPORTING
ORDER BY I.IMPACTCODE, I.SITECODE
;

-- 4730 = ZÁZNAMY, KTERÉ MAJÍ SICE V POŘÁDKU IMPACTCODE, ALE JEJICH DESCRIPTION NEODPOVÍDÁ ŽÁDNÉMU DESCRIPTION_USE_FOR_REPORTING V REFERENČNÍ TABULCE.
WITH REF_DESC AS (
    SELECT DISTINCT DESCRIPTION_USE_FOR_REPORTING
    FROM REF_CODES
                 )
SELECT I.*
FROM IMPACT AS I
INNER JOIN REF_CODES AS R_CODE 
    ON I.IMPACTCODE = R_CODE.CODE
LEFT JOIN REF_DESC AS R_DESC 
    ON I.DESCRIPTION = R_DESC.DESCRIPTION_USE_FOR_REPORTING
WHERE R_DESC.DESCRIPTION_USE_FOR_REPORTING IS NULL
ORDER BY I.IMPACTCODE, I.SITECODE
;

-- 4 - O KTERÉ KONKRÉTNĚ DESCRIPTION Z TABULKY IMPACT JDE?
WITH REF_DESC AS (
    SELECT DISTINCT DESCRIPTION_USE_FOR_REPORTING
    FROM REF_CODES
                 )
SELECT 
    I.DESCRIPTION AS DESCRIPTION_NOT_IN_REF,
    I.IMPACTCODE,
    COUNT(*) AS POCET_VYSKYTU
FROM IMPACT AS I
INNER JOIN REF_CODES AS R_CODE 
    ON I.IMPACTCODE = R_CODE.CODE
LEFT JOIN REF_DESC AS R_DESC 
    ON I.DESCRIPTION = R_DESC.DESCRIPTION_USE_FOR_REPORTING
WHERE R_DESC.DESCRIPTION_USE_FOR_REPORTING IS NULL
GROUP BY I.DESCRIPTION, I.IMPACTCODE
ORDER BY POCET_VYSKYTU DESC
;

/*
            FOREST AND PLANTATION MANAGEMENT  & USE	B02	2591 (SPRÁVNĚ FOREST AND PLANTATION MANAGEMENT & USE)
            ABANDONMENT / LACK OF  MOWING	A03.03	1886 (SPRÁVNĚ ABANDONMENT / LACK OF MOWING)
            LACK OF  FLOODING	J02.04.02	200 (SPRÁVNĚ LACK OF FLOODING)
            GROUNDWATER ABSTRACTIONS FOR  PUBLIC WATER SUPPLY	J02.07.02	53 (SPRÁVNĚ GROUNDWATER ABSTRACTIONS FOR PUBLIC WATER SUPPLY)
            */

            --==> ZJIŠTĚNÍ: NEPLECHU DĚLAJÍ JEN 4 UNIKÁTNÍ HODNOTY - VŽDY JDE O DVOJITOU MEZERU:
                    -- DALO SE ZJISTIT I TAKTO:

                        SELECT DISTINCT DESCRIPTION
                        FROM IMPACT
                        WHERE DESCRIPTION ILIKE '%  %'
                        ;

-- ==> ZÁVĚR: NAMÍSTO OPRAVOVÁNÍ DESCRIPTION PROVEDU JOIN S TABULKOU REF_CODES = PŘIPOJÍM SI PŘES IMPACTCODE = CODE DESCRIPTION (OVĚŘILA JSEM, ŽE DESCRIPTION HODNOTY ODPOVÍDAJÍ DESCRIPTION_USE_FOR_REPORTING HODNOTÁM.


-- OCCURRENCE:
----------------------------------------------------------------------------------------------------------------

-- 191 173 = POČET VALIDNÍCH ZÁZNAMŮ S VYPLNĚNÝM OCCURRENCE
SELECT *
FROM IMPACT AS I
INNER JOIN REF_CODES AS R ON
    I.IMPACTCODE = R.CODE
WHERE OCCURRENCE <> '' AND OCCURRENCE IS NOT NULL
;

-- 2 767 = POČET VALIDNÍCH ZÁZNAMŮ BEZ VYPLNĚNÉHO OCCURRENCE
SELECT *
FROM IMPACT AS I
INNER JOIN REF_CODES AS R ON
    I.IMPACTCODE = R.CODE
WHERE OCCURRENCE = '' OR OCCURRENCE IS NULL
;

SELECT DISTINCT OCCURRENCE 
FROM IMPACT
;

-- '', A, -


-- IMPACT_TYPE:
----------------------------------------------------------------------------------------------------------------

-- 189 603 = POČET VALIDNÍCH ZÁZNAMŮ S VYPLNĚNÝM IMPACT_TYPE
SELECT *
FROM IMPACT AS I
INNER JOIN REF_CODES AS R ON
    I.IMPACTCODE = R.CODE
WHERE IMPACT_TYPE <> '' AND IMPACT_TYPE IS NOT NULL
;

-- 4 337 = POČET VALIDNÍCH ZÁZNAMŮ BEZ VYPLNĚNÉHO IMPACT_TYPE
SELECT *
FROM IMPACT AS I
INNER JOIN REF_CODES AS R ON
    I.IMPACTCODE = R.CODE
WHERE IMPACT_TYPE = '' OR IMPACT_TYPE IS NULL
;

SELECT DISTINCT IMPACT_TYPE 
FROM IMPACT
;

-- '', P, N


-- INTENSITY:
----------------------------------------------------------------------------------------------------------------

-- 190 618 = POČET VALIDNÍCH ZÁZNAMŮ S VYPLNĚNÝM INTENSITY
SELECT *
FROM IMPACT AS I
INNER JOIN REF_CODES AS R ON
    I.IMPACTCODE = R.CODE
WHERE INTENSITY <> '' AND INTENSITY IS NOT NULL
;

-- 3 322 = POČET VALIDNÍCH ZÁZNAMŮ BEZ VYPLNĚNÉHO INTENSITY
SELECT *
FROM IMPACT AS I
INNER JOIN REF_CODES AS R ON
    I.IMPACTCODE = R.CODE
WHERE INTENSITY = '' OR INTENSITY IS NULL
;

SELECT DISTINCT INTENSITY 
FROM IMPACT
;

-- A, '', O, X, C, E, I

 
-- JE KAŽDÁ KOMBINACE SITECODE A IMPACTCODE V TABULCE IMPACT_CLEAN JENOM JEDNOU?
--------------------------------------------------------------------------------------------------------------

-- 14 062 = 
SELECT 
    I.IMPACTCODE,
    I.SITECODE,
    COUNT(*) AS CNT
FROM IMPACT_CLEAN AS I
INNER JOIN REF_CODES AS R ON
    I.IMPACTCODE = R.CODE
GROUP BY I.IMPACTCODE, I.SITECODE
HAVING COUNT(*) > 1
ORDER BY CNT DESC
;

-- 30 354
SELECT I.*
FROM IMPACT_CLEAN AS I
INNER JOIN REF_CODES AS R 
    ON I.IMPACTCODE = R.CODE
WHERE (I.IMPACTCODE, I.SITECODE) IN (
    SELECT 
        I2.IMPACTCODE,
        I2.SITECODE
    FROM IMPACT_CLEAN AS I2
    INNER JOIN REF_CODES AS R2 
        ON I2.IMPACTCODE = R2.CODE
    GROUP BY I2.IMPACTCODE, I2.SITECODE
    HAVING COUNT(*) > 1
)
ORDER BY I.IMPACTCODE, I.SITECODE
;

-- ZK.
SELECT *
FROM IMPACT_CLEAN
WHERE IMPACTCODE = 'A01' AND SITECODE = 'AT1304000'


-- ZAMĚŘENÍ NA NÁRODNÍ PARKY V ČR:

-- VŠECHNY PLOŠKY A, B, C V ČR:
SELECT *
FROM NATURA2000SITES_TABLEAU
WHERE COUNTRY_CODE = 'CZ' 
-- ND SITE_TYPE = 'C'
ORDER BY SITE_NAME
;

-- VŠECHNY PLOŠKY A, B, C V NÁRODNÍCH PARCÍCH ČR:
SELECT *
FROM NATURA2000SITES_TABLEAU
WHERE SITE_NAME IN ('ŠUMAVA', 'KRKONOŠE', 'ČESKÉ ŠVÝCARSKO', 'PODYJÍ')
ORDER BY SITE_NAME
;

-- VŠECHNY PLOŠKY A, B, C V NÁRODNÍCH PARCÍCH ČR + LABSKÉ PÍSKOVCE:
SELECT *
FROM NATURA2000SITES_TABLEAU
WHERE SITE_NAME IN ('ŠUMAVA', 'KRKONOŠE', 'ČESKÉ ŠVÝCARSKO', 'PODYJÍ')
    OR SITE_NAME LIKE 'LABSKÉ PÍSKOVCE'
ORDER BY SITE_NAME, SITE_TYPE
;

-- ŠUMAVA
SELECT *
FROM NATURA2000SITES_TABLEAU
WHERE SITE_NAME IN ('ŠUMAVA')
ORDER BY SITE_NAME, SITE_TYPE
;

-- VRÁTÍ 10 NEJZATÍŽENĚJŠÍCH EVL V ČR (NEJVYŠŠÍ POČET NEGATIVNÍCH IMPACTŮ NA EVL)
SELECT N.SITE_NAME
    , COUNT(DISTINCT I.IMPACTCODE) AS POCET_UNIKATNICH_DESCRIPTION
FROM IMPACT_CLEAN AS I
JOIN NATURA2000SITES_TABLEAU_2 AS N ON N.SITE_CODE = I.SITECODE
WHERE I.COUNTRY_CODE = 'CZ'
    AND I.IMPACT_TYPE = 'N'
    AND N.SITE_TYPE = 'B'
    AND I.OCCURRENCE = 'IN'
    AND I.INTENSITY IN ('HIGH', 'MEDIUM', 'LOW')
GROUP BY N.SITE_NAME
ORDER BY POCET_UNIKATNICH_DESCRIPTION DESC
LIMIT 10
;

/*
----------------------------
OVERVIEW: TABULKA IMPACT:
----------------------------

 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   SITECODE       203974  non-null  object
 1   IMPACTCODE     203938  non-null  object
 2   DESCRIPTION    203527  non-null  object
 3   INTENSITY      201004  non-null  object
 4   POLLUTIONCODE  4772    non-null  object
 5   OCCURRENCE     201096  non-null  object
 6   IMPACT_TYPE    200006  non-null  object

----------------------------
DOKUMENTACE:
----------------------------

SITECODE
ED: Unique code witch forms the key-item within the database.
VD: The unique code comprises nine characters and consists of two components. The first two codes are the country code the remaining seven characters, which serve to create a unique alphanumeric code for each site.

IMPACTCODE
ED: Human activity and natural process that may have an influence, either positive or negative, on the conservation and management of the site.

DESCRIPTION
ED: Inside or outside the surrounding of the site. The surrounding is the area where the outside impacts and activities may effect the integrity of the site.

INTENSITY
ED: Indicates the rank of the impact.
VD: HIGH, MEDIUM, LOW

POLLUTIONCODE
ED: Code of the type of pollution. VD: Nitrogen input - N, Phosphor/Phosphate input -P, Acidification -A, Toxic inorganic chemicals -T, Toxic organic chemicals -O, Mixed pollution-X

OCCURRENCE
ED: Indicate whether the influence is positive (+) or negative (-).

IMPACT_TYPE
ED: Indicate whether the influence is positive (P) or negative (N).

*/